### ISSUE TITLE
Additional 'Unassigned' and 'NA' values can be in the field_value variable 

### ISSUE THREAD

**Issue by darckly** [JamaSoftware/risk_calculator#1]
The P1, P2 and Severity drop-down lists can also have the 'Unassigned' or 'NA' values.
Please update the script with the following statements:
224:         if field_value is None or field_value is {} or field_value is "" **or field_value == 'Unassigned' or field_value == 'NA'**:
            field_value = 0

**Comment by casakawa-jama** [comment]
thanks, i added this into the code.
